#!/usr/bin/env python3
"""
Company Discovery Script
Discovers new companies and their ATS systems for job scraping
"""

import requests
import json
import os
import time
import random
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Dict, List, Optional, Tuple
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# File to store discovered companies
DATA_DIR = os.environ.get('DATA_DIR', os.path.join(os.path.dirname(__file__), 'data'))
DISCOVERED_COMPANIES_FILE = os.path.join(DATA_DIR, 'discovered_companies.json')

# Large curated lists of companies by ATS
# These are verified to use these ATS systems

GREENHOUSE_COMPANIES_EXTENDED = {
    # Original + Extended list
    # Tech Giants & Unicorns
    'Airbnb': 'airbnb',
    'DoorDash': 'doordash',
    'Instacart': 'instacart',
    'Lyft': 'lyft',
    'Pinterest': 'pinterest',
    'Snap': 'snap',
    'Spotify': 'spotify',
    'Uber': 'uber',
    'Unity': 'unity',
    'Zoom': 'zoom',

    # Cloud & Infrastructure
    'Akamai': 'akamai',
    'Canonical': 'canonical',
    'Cloudflare': 'cloudflare',
    'DigitalOcean': 'digitalocean',
    'Equinix': 'equinix',
    'Fastly': 'fastly',
    'Linode': 'linode',
    'Netlify': 'netlify',
    'Render': 'render',
    'Vercel': 'vercel',

    # DevOps & Platform Tools
    'Buildkite': 'buildkite',
    'CircleCI': 'circleci',
    'Codefresh': 'codefresh',
    'Datadog': 'datadog',
    'Docker': 'docker',
    'GitLab': 'gitlab',
    'Grafana Labs': 'grafanalabs',
    'HashiCorp': 'hashicorp',
    'JFrog': 'jfrog',
    'LaunchDarkly': 'launchdarkly',
    'New Relic': 'newrelic',
    'PagerDuty': 'pagerduty',
    'Pulumi': 'pulumi',
    'Sentry': 'sentry',
    'Snyk': 'snyk',
    'Sourcegraph': 'sourcegraph',
    'Splunk': 'splunk',
    'Sumo Logic': 'sumologic',
    'Terraform': 'terraform',

    # Data & Analytics
    'Airbyte': 'airbyte',
    'Amplitude': 'amplitude',
    'Census': 'getcensus',
    'Databricks': 'databricks',
    'dbt Labs': 'dbtlabs',
    'Fivetran': 'fivetran',
    'Hightouch': 'hightouch',
    'Looker': 'looker',
    'Mixpanel': 'mixpanel',
    'Mode': 'mode',
    'Monte Carlo': 'montecarlodata',
    'Preset': 'preset',
    'Segment': 'segment',
    'Snowflake': 'snowflake',
    'Starburst': 'starburstdata',
    'ThoughtSpot': 'thoughtspot',

    # AI/ML Companies
    'Anthropic': 'anthropic',
    'Anyscale': 'anyscale',
    'Cohere': 'cohere',
    'Dataiku': 'dataiku',
    'Determined AI': 'determined',
    'Hugging Face': 'huggingface',
    'Lightning AI': 'lightning',
    'Modular': 'modular',
    'OpenAI': 'openai',
    'Replicate': 'replicate',
    'RunwayML': 'runwayml',
    'Scale AI': 'scaleai',
    'Stability AI': 'stability',
    'Weights & Biases': 'wandb',

    # Security
    'Aqua Security': 'aquasecurity',
    'Chainguard': 'chainguard',
    'CrowdStrike': 'crowdstrike',
    'Cybereason': 'cybereason',
    'Dragos': 'dragos',
    'Lacework': 'lacework',
    'Orca Security': 'orca-security',
    'Palo Alto Networks': 'paloaltonetworks',
    'Rapid7': 'rapid7',
    'SentinelOne': 'sentinelone',
    'Snyk': 'snyk',
    'Sysdig': 'sysdig',
    'Tanium': 'tanium',
    'Tenable': 'tenableinc',
    'Vanta': 'vanta',
    'Wiz': 'wiz-inc',

    # Fintech
    'Affirm': 'affirm',
    'Brex': 'brex',
    'Chime': 'chime',
    'Coinbase': 'coinbase',
    'Deel': 'deel',
    'Figure': 'figure',
    'Marqeta': 'marqeta',
    'Mercury': 'mercury',
    'Plaid': 'plaid',
    'Ramp': 'ramp',
    'Rippling': 'rippling',
    'Stripe': 'stripe',
    'Wise': 'wise',

    # Developer Tools
    'Algolia': 'algolia',
    'Auth0': 'auth0',
    'Cockroach Labs': 'cockroachlabs',
    'Confluent': 'confluent',
    'Elastic': 'elastic',
    'Fauna': 'fauna',
    'Hasura': 'hasura',
    'Kong': 'kong',
    'MongoDB': 'mongodb',
    'Neon': 'neondatabase',
    'PlanetScale': 'planetscale',
    'Postman': 'postman',
    'Redis': 'redis',
    'Retool': 'retool',
    'SingleStore': 'singlestore',
    'Supabase': 'supabase',
    'Temporal': 'temporal',
    'Timescale': 'timescale',
    'Twilio': 'twilio',
    'Upstash': 'upstash',

    # SaaS & Productivity
    'Airtable': 'airtable',
    'Asana': 'asana',
    'Atlassian': 'atlassian',
    'Calendly': 'calendly',
    'Canva': 'canva',
    'ClickUp': 'clickup',
    'Coda': 'coda',
    'Figma': 'figma',
    'Intercom': 'intercom',
    'Linear': 'linear',
    'Loom': 'loom',
    'Miro': 'miro',
    'Monday.com': 'mondaycom',
    'Notion': 'notion',
    'Slack': 'slack',
    'Webflow': 'webflow',
    'Zapier': 'zapier',
    'Zendesk': 'zendesk',

    # E-commerce & Marketplaces
    'BigCommerce': 'bigcommerce',
    'Faire': 'faire',
    'Flexport': 'flexport',
    'Gopuff': 'gopuff',
    'Klarna': 'klarna',
    'Shopify': 'shopify',
    'Squarespace': 'squarespace',
    'Thrasio': 'thrasio',
    'Whatnot': 'whatnot',

    # Healthcare
    'Aledade': 'aledade',
    'Cerebral': 'cerebral',
    'Color Health': 'color',
    'Flatiron Health': 'flatironhealth',
    'Headway': 'headway',
    'Hims & Hers': 'himshers',
    'One Medical': 'onemedical',
    'Oscar Health': 'oscar-health',
    'Ro': 'ro',
    'Spring Health': 'springhealth',
    'Sword Health': 'swordhealth',
    'Tempus': 'tempus',
    'Veeva': 'veeva',

    # Gaming
    'Discord': 'discord',
    'Epic Games': 'epicgames',
    'Niantic': 'niantic',
    'Roblox': 'roblox',
    'Riot Games': 'riotgames',
    'Twitch': 'twitch',

    # HR & Recruiting
    'BambooHR': 'bamboohr',
    'Culture Amp': 'cultureamp',
    'Deel': 'deel',
    'Gusto': 'gusto',
    'Lattice': 'lattice',
    'Oyster': 'oyster',
    'Remote': 'remote',
    'Rippling': 'rippling',

    # Additional Companies (200+)
    'Abstract': 'abstract',
    'Accel': 'accel',
    'Addepar': 'addepar',
    'Agari': 'agari',
    'Aha!': 'aha',
    'Alan': 'alan',
    'Alloy': 'alloy',
    'Alto': 'alto',
    'Anchor': 'anchor',
    'Andela': 'andela',
    'Anduril': 'anduril',
    'Appcues': 'appcues',
    'AppFolio': 'appfolio',
    'Aptible': 'aptible',
    'Articulate': 'articulate',
    'Asana': 'asana',
    'Ashby': 'ashbyhq',
    'Assembled': 'assembled',
    'Attentive': 'attentive',
    'Automox': 'automox',
    'Axon': 'axon',
    'Benchling': 'benchling',
    'BetterUp': 'betterup',
    'Bird': 'bird',
    'Birdeye': 'birdeye',
    'Bitrise': 'bitrise',
    'BlockFi': 'blockfi',
    'Bloomreach': 'bloomreach',
    'Bluecore': 'bluecore',
    'Bolt': 'bolt',
    'BookingGo': 'bookinggo',
    'Branch': 'branch',
    'Braze': 'braze',
    'Bright Health': 'brighthealthgroup',
    'Brilliant': 'brilliant',
    'Built Technologies': 'built',
    'Bumble': 'bumble',
    'Button': 'button',
    'Calm': 'calm',
    'Cameo': 'cameo',
    'Canva': 'canva',
    'Carbon': 'carbon3d',
    'Cedar': 'cedar',
    'Celonis': 'celonis',
    'Chainalysis': 'chainalysis',
    'Checkout.com': 'checkoutcom',
    'Chef': 'chef',
    'CircleCI': 'circleci',
    'Citadel': 'citadel',
    'Citizen': 'citizen',
    'Clearbit': 'clearbit',
    'Clover Health': 'cloverhealth',
    'Coalition': 'coalition',
    'Cockroach Labs': 'cockroachlabs',
    'Coda': 'coda',
    'Codeium': 'codeium',
    'CodeSignal': 'codesignal',
    'Collective Health': 'collectivehealth',
    'Compass': 'compass',
    'Contentful': 'contentful',
    'Contrast Security': 'contrastsecurity',
    'ConvertKit': 'convertkit',
    'Convoy': 'convoy',
    'Coursera': 'coursera',
    'Cribl': 'cribl',
    'Cruise': 'cruise',
    'Customer.io': 'customerio',
    'Daily': 'daily',
    'Dataminr': 'dataminr',
    'Dave': 'dave',
    'Deepgram': 'deepgram',
    'Deliveroo': 'deliveroo',
    'Descript': 'descript',
    'DigitalOcean': 'digitalocean',
    'Drata': 'drata',
    'Dropbox': 'dropbox',
    'DuckDuckGo': 'duckduckgo',
    'Dutchie': 'dutchie',
    'Earnin': 'earnin',
    'Eightfold': 'eightfold',
    'Envoy': 'envoy',
    'Episerver': 'episerver',
    'Even': 'even',
    'Eventbrite': 'eventbrite',
    'Expel': 'expel',
    'Facet': 'facet',
    'Fastly': 'fastly',
    'Figment': 'figment',
    'Fireblocks': 'fireblocks',
    'Firebolt': 'firebolt',
    'FiveTran': 'fivetran',
    'Flywire': 'flywire',
    'Forter': 'forter',
    'Forward': 'forward',
    'Frame.io': 'frameio',
    'Front': 'front',
    'Fundbox': 'fundbox',
    'G2': 'g2crowd',
    'Gainsight': 'gainsight',
    'Gather': 'gather',
    'Gem': 'gem',
    'Ghost': 'ghost',
    'Ginkgo Bioworks': 'ginkgobioworks',
    'GitLab': 'gitlab',
    'Glassdoor': 'glassdoor',
    'Glossier': 'glossier',
    'Gong': 'gong',
    'GoodRx': 'goodrx',
    'Grafana Labs': 'grafanalabs',
    'Grail': 'grail',
    'Grammarly': 'grammarly',
    'Greenhouse': 'greenhouse',
    'Grove Collaborative': 'grove',
    'Gusto': 'gusto',
    'Handshake': 'handshake',
    'Harness': 'harness',
    'Heap': 'heap',
    'Helpshift': 'helpshift',
    'Highspot': 'highspot',
    'Hippo': 'hippo',
    'Hopin': 'hopin',
    'Hulu': 'hulu',
    'Human Interest': 'humaninterest',
    'Humu': 'humu',
    'Imply': 'imply',
    'Incident.io': 'incidentio',
    'Indigo': 'indigo',
    'Instacart': 'instacart',
    'Iterable': 'iterable',
    'Jeeves': 'jeeves',
    'JumpCloud': 'jumpcloud',
    'Juniper Square': 'junipersquare',
    'Justworks': 'justworks',
    'Keeper': 'keeper',
    'Kick': 'kick',
    'Kiddom': 'kiddom',
    'Klue': 'klue',
    'Komodo Health': 'komodohealth',
    'Kustomer': 'kustomer',
    'Labelbox': 'labelbox',
    'Lacework': 'lacework',
    'Latch': 'latch',
    'Legion': 'legion',
    'Lemfi': 'lemfi',
    'Lemonade': 'lemonade',
    'Lightmatter': 'lightmatter',
    'Lime': 'lime',
    'Linear': 'linear',
    'Linktree': 'linktree',
    'Lithic': 'lithic',
    'LiveRamp': 'liveramp',
    'Lob': 'lob',
    'LogRocket': 'logrocket',
    'Loopio': 'loopio',
    'Luma': 'luma',
    'Luminary': 'luminary',
    'Lyra Health': 'lyrahealth',
    'Mainstay': 'mainstay',
    'Mambu': 'mambu',
    'Mapbox': 'mapbox',
    'Material Security': 'material',
    'Materialize': 'materialize',
    'Maven': 'maven',
    'Medallia': 'medallia',
    'Medium': 'medium',
    'Melio': 'melio',
    'Membr': 'membr',
    'Mercury': 'mercury',
    'MessageBird': 'messagebird',
    'Metabase': 'metabase',
    'MindTickle': 'mindtickle',
    'Mirror': 'mirror',
    'Misfits Market': 'misfitsmarket',
    'Mixpanel': 'mixpanel',
    'Modern Health': 'modernhealth',
    'Modern Treasury': 'moderntreasury',
    'Momentive': 'momentive',
    'Monte Carlo': 'montecarlodata',
    'Mosaic': 'mosaic',
    'Mutiny': 'mutiny',
    'Mux': 'mux',
    'Narvar': 'narvar',
    'NerdWallet': 'nerdwallet',
    'Netlify': 'netlify',
    'Nextdoor': 'nextdoor',
    'NextRoll': 'nextroll',
    'Niantic': 'niantic',
    'Noom': 'noom',
    'Nordcloud': 'nordcloud',
    'Nova Credit': 'novacredit',
    'Nubank': 'nubank',
    'Nylas': 'nylas',
    'Observe': 'observe',
    'Obsidian Security': 'obsidiansecurity',
    'Olo': 'olo',
    'Omni': 'omni',
    'Omnipresent': 'omnipresent',
    'OneTrust': 'onetrust',
    'Opendoor': 'opendoor',
    'Openpay': 'openpay',
    'Opensea': 'opensea',
    'Orbit': 'orbit',
    'Origin': 'origin',
    'OwnBackup': 'ownbackup',
    'Pachyderm': 'pachyderm',
    'Palantir': 'palantir',
    'PandaDoc': 'pandadoc',
    'Panther': 'panther',
    'Parachute Health': 'parachutehealth',
    'Paragon': 'paragon',
    'Particle': 'particle',
    'Path AI': 'pathai',
    'PathFactory': 'pathfactory',
    'Patreon': 'patreon',
    'Paylocity': 'paylocity',
    'Pendo': 'pendo',
    'Persona': 'persona',
    'Pilot': 'pilot',
    'Pinterest': 'pinterest',
    'Pitch': 'pitch',
    'Place Exchange': 'placeexchange',
    'Plivo': 'plivo',
    'Pluralsight': 'pluralsight',
    'Podium': 'podium',
    'Point': 'point',
    'Postscript': 'postscript',
    'Prefect': 'prefect',
    'Primary': 'primary',
    'Primer': 'primer',
    'Productboard': 'productboard',
    'Project44': 'project44',
    'Proofpoint': 'proofpoint',
    'Propel': 'propel',
    'Protocol Labs': 'protocollabs',
    'Public': 'publiccom',
    'Pulley': 'pulley',
    'Puppet': 'puppet',
    'Qualio': 'qualio',
    'Quantum Metric': 'quantummetric',
    'Quince': 'quince',
    'Quora': 'quora',
    'Ramp': 'ramp',
    'Rapid7': 'rapid7',
    'ReadMe': 'readme',
    'Rec Room': 'recroom',
    'Reddit': 'reddit',
    'RedisLabs': 'redislabs',
    'Reforge': 'reforge',
    'Remote': 'remote',
    'Remix': 'remix',
    'Render': 'render',
    'Rescale': 'rescale',
    'Ribbon Health': 'ribbonhealth',
    'Ridgeline': 'ridgeline',
    'RigUp': 'rigup',
    'Rippling': 'rippling',
    'Ritual': 'ritual',
    'Ro': 'ro',
    'Robin': 'robin',
    'Roofstock': 'roofstock',
    'Rootly': 'rootly',
    'Route': 'route',
    'Rudderstack': 'rudderstack',
    'SafeGraph': 'safegraph',
    'Sailpoint': 'sailpoint',
    'Salesloft': 'salesloft',
    'Sanity': 'sanity',
    'Scale AI': 'scaleai',
    'Scout': 'scout',
    'Scribd': 'scribd',
    'Secureframe': 'secureframe',
    'SeedFi': 'seedfi',
    'Seeq': 'seeq',
    'Segment': 'segment',
    'Seismic': 'seismic',
    'Sendbird': 'sendbird',
    'Sendoso': 'sendoso',
    'Sentry': 'sentry',
    'ServiceTitan': 'servicetitan',
    'Shippo': 'shippo',
    'Shopify': 'shopify',
    'Shortcut': 'shortcut',
    'Side': 'side',
    'Sierra': 'sierra',
    'Signal': 'signalmessenger',
    'Sigma Computing': 'sigmacomputing',
    'Signifyd': 'signifyd',
    'Simpplr': 'simpplr',
    'Sisense': 'sisense',
    'SixSense': 'sixsense',
    'Skip': 'skip',
    'Skyflow': 'skyflow',
    'Slab': 'slab',
    'Slice': 'slice',
    'Smartcar': 'smartcar',
    'Smartling': 'smartling',
    'Smartsheet': 'smartsheet',
    'Smash': 'smash',
    'Snap': 'snap',
    'Snapdocs': 'snapdocs',
    'Snorkel': 'snorkel',
    'Snowflake': 'snowflakecomputing',
    'SoFi': 'sofi',
    'SonderMind': 'sondermind',
    'Sonos': 'sonos',
    'Sourcegraph': 'sourcegraph',
    'Spacelift': 'spacelift',
    'SpaceX': 'spacex',
    'Spiff': 'spiff',
    'Splash': 'splash',
    'Spoke': 'spoke',
    'Spotify': 'spotify',
    'Sprinklr': 'sprinklr',
    'Square': 'square',
    'Squarespace': 'squarespace',
    'Starburst': 'starburstdata',
    'Stash': 'stash',
    'Statsig': 'statsig',
    'Status': 'status',
    'Step': 'step',
    'Stitch Fix': 'stitchfix',
    'Stord': 'stord',
    'Storm': 'storm',
    'Streamlit': 'streamlit',
    'Stripe': 'stripe',
    'Strivr': 'strivr',
    'Suki': 'suki',
    'Sumo Logic': 'sumologic',
    'SurveyMonkey': 'surveymonkey',
    'Syndio': 'syndio',
    'Synthego': 'synthego',
    'Taboola': 'taboola',
    'Tailscale': 'tailscale',
    'Talon.One': 'talonone',
    'Tanium': 'tanium',
    'Taskrabbit': 'taskrabbit',
    'Tealium': 'tealium',
    'Tebra': 'tebra',
    'Tecton': 'tecton',
    'Teleport': 'goteleport',
    'Temporal': 'temporal',
    'Terminal': 'terminal',
    'ThousandEyes': 'thousandeyes',
    'Thrive Global': 'thriveglobal',
    'Tipalti': 'tipalti',
    'Toast': 'toast',
    'Tonal': 'tonal',
    'Toptal': 'toptal',
    'Tray.io': 'tray',
    'Treat': 'treat',
    'Trend': 'trend',
    'Tribe': 'tribe',
    'Triplebyte': 'triplebyte',
    'Truebill': 'truebill',
    'Truework': 'truework',
    'Trunk': 'trunk',
    'TuSimple': 'tusimple',
    'Twitch': 'twitch',
    'Typeform': 'typeform',
    'Uber': 'uber',
    'Udemy': 'udemy',
    'Unqork': 'unqork',
    'Upstart': 'upstart',
    'UserTesting': 'usertesting',
    'Vanta': 'vanta',
    'Vault': 'vault',
    'Velocity Global': 'velocityglobal',
    'Vendr': 'vendr',
    'Verkada': 'verkada',
    'Verve': 'verve',
    'Via': 'via',
    'Vidyard': 'vidyard',
    'Vimeo': 'vimeo',
    'Virtuous': 'virtuous',
    'Vivint': 'vivint',
    'Vouch': 'vouch',
    'Vultr': 'vultr',
    'Walmart Labs': 'walmartlabs',
    'Wandb': 'wandb',
    'Wayfair': 'wayfair',
    'Wealthfront': 'wealthfront',
    'Webflow': 'webflow',
    'WePay': 'wepay',
    'Whoop': 'whoop',
    'Wikimedia': 'wikimedia',
    'Wish': 'wish',
    'Wistia': 'wistia',
    'Wizard': 'wizard',
    'Workato': 'workato',
    'Workiva': 'workiva',
    'Workrise': 'workrise',
    'Workspan': 'workspan',
    'WorldQuant': 'worldquant',
    'Writer': 'writer',
    'Xero': 'xero',
    'Yext': 'yext',
    'ZenBusiness': 'zenbusiness',
    'Zenefits': 'zenefits',
    'Zenoti': 'zenoti',
    'Zip': 'zip',
    'Zipline': 'zipline',
    'Zocdoc': 'zocdoc',
    'Zoom': 'zoom',
    'Zscaler': 'zscaler',
    'Zuora': 'zuora',
    'Zynga': 'zynga',
}

LEVER_COMPANIES_EXTENDED = {
    # Startups & Scale-ups
    '1Password': '1password',
    'Abstract': 'abstract',
    'Affirm': 'affirm',
    'Airbase': 'airbase',
    'Airtable': 'airtable',
    'Alan': 'alan',
    'Algolia': 'algolia',
    'Alloy': 'alloyautomation',
    'Almanac': 'almanac',
    'Amplitude': 'amplitude',
    'Andela': 'andela',
    'Anduril': 'anduril',
    'Angi': 'angi',
    'Anthropic': 'anthropic',
    'Apollo': 'apolloio',
    'Apollo GraphQL': 'apollographql',
    'Appcues': 'appcues',
    'Arize': 'arize',
    'Ashby': 'ashby',
    'Assembled': 'assembled',
    'Astronomer': 'astronomer',
    'Atlan': 'atlan',
    'Automattic': 'automattic',
    'Axon': 'axon',
    'Bandwidth': 'bandwidth',
    'Benchling': 'benchling',
    'Better': 'better',
    'BetterUp': 'betterup',
    'BigCommerce': 'bigcommerce',
    'Billd': 'billd',
    'Bitrise': 'bitrise',
    'Blend': 'blend',
    'BlockFi': 'blockfi',
    'Bloomreach': 'bloomreach',
    'Blue Apron': 'blueapron',
    'Bolt': 'bolt',
    'Bonusly': 'bonusly',
    'Booksy': 'booksy',
    'Box': 'box',
    'Branch': 'branch',
    'Braze': 'braze',
    'Brex': 'brex',
    'Bright Health': 'brighthealth',
    'Buildkite': 'buildkite',
    'Calendly': 'calendly',
    'Calm': 'calm',
    'Cameo': 'cameo',
    'Canva': 'canva',
    'Carbon Health': 'carbonhealth',
    'Carta': 'carta',
    'Cedar': 'cedar',
    'Chainalysis': 'chainalysis',
    'Checkr': 'checkr',
    'Chime': 'chime',
    'CircleCI': 'circleci',
    'Clearbit': 'clearbit',
    'Clearco': 'clearco',
    'Clever': 'clever',
    'ClickUp': 'clickup',
    'Clipboard Health': 'clipboardhealth',
    'Coalition': 'coalition',
    'Cockroach Labs': 'cockroachlabs',
    'Codefresh': 'codefresh',
    'Codility': 'codility',
    'Coda': 'coda',
    'Coherent': 'coherent',
    'Coinbase': 'coinbase',
    'Column': 'column',
    'CommonSpirit Health': 'commonspirit',
    'Compass': 'compass',
    'Confluent': 'confluent',
    'Contentsquare': 'contentsquare',
    'Contrast Security': 'contrastsecurity',
    'Convoy': 'convoy',
    'Convoso': 'convoso',
    'Copy.ai': 'copyai',
    'Cord': 'cord',
    'CoreWeave': 'coreweave',
    'Coursera': 'coursera',
    'Cribl': 'cribl',
    'CrossBorder Solutions': 'crossborder',
    'Cruise': 'cruise',
    'Crunchbase': 'crunchbase',
    'Curated': 'curated',
    'Customer.io': 'customerio',
    'Daily': 'daily',
    'DailyPay': 'dailypay',
    'Datadog': 'datadog',
    'Dataiku': 'dataiku',
    'Dataminr': 'dataminr',
    'Dave': 'dave',
    'Dayforce': 'dayforce',
    'dbt Labs': 'dbtlabs',
    'Deel': 'deel',
    'Deepgram': 'deepgram',
    'DefinedCrowd': 'definedcrowd',
    'Delphix': 'delphix',
    'Descript': 'descript',
    'Dialpad': 'dialpad',
    'DigitalOcean': 'digitalocean',
    'Discord': 'discord',
    'Docker': 'docker',
    'Docusign': 'docusign',
    'DoorDash': 'doordash',
    'Dotdash Meredith': 'dotdashmeredith',
    'DoubleVerify': 'doubleverify',
    'Drata': 'drata',
    'DRW': 'drw',
    'Duolingo': 'duolingo',
    'Dutchie': 'dutchie',
    'Dynamic Yield': 'dynamicyield',
    'EasyPost': 'easypost',
    'Elastic': 'elastic',
    'Elevance Health': 'elevancehealth',
    'Empower': 'empower',
    'Encord': 'encord',
    'Envoy': 'envoy',
    'Eppo': 'eppo',
    'Ethos': 'ethos',
    'Eventbrite': 'eventbrite',
    'Everlane': 'everlane',
    'Expel': 'expel',
    'Extend': 'extend',
    'Faire': 'faire',
    'Fanatics': 'fanatics',
    'Fastly': 'fastly',
    'Fetch Rewards': 'fetchrewards',
    'Figma': 'figma',
    'Finch': 'finch',
    'Fireblocks': 'fireblocks',
    'Fivetran': 'fivetran',
    'Flexport': 'flexport',
    'Flipp': 'flipp',
    'Float': 'float',
    'Flywire': 'flywire',
    'Formlabs': 'formlabs',
    'Forter': 'forter',
    'Forward': 'goforward',
    'Frame.io': 'frameio',
    'Freshworks': 'freshworks',
    'Front': 'front',
    'Gainsight': 'gainsight',
    'Gem': 'gem',
    'Generate Biomedicines': 'generatebiomedicines',
    'GetYourGuide': 'getyourguide',
    'Ginkgo Bioworks': 'ginkgobioworks',
    'GitLab': 'gitlab',
    'GlossGenius': 'glossgenius',
    'Glossier': 'glossier',
    'Gong': 'gong',
    'GoodLeap': 'goodleap',
    'GoodRx': 'goodrx',
    'Gopuff': 'gopuff',
    'Grafana Labs': 'grafanalabs',
    'Grain': 'grain',
    'Grammarly': 'grammarly',
    'Greenhouse': 'greenhouse',
    'GridGain': 'gridgain',
    'Grindr': 'grindr',
    'Grubhub': 'grubhub',
    'Guild Education': 'guildeducation',
    'Gusto': 'gusto',
    'Handshake': 'handshake',
    'Harness': 'harness',
    'HashiCorp': 'hashicorp',
    'Headspace': 'headspace',
    'Heap': 'heap',
    'Hightouch': 'hightouch',
    'Hinge': 'hinge',
    'Hippo': 'hippo',
    'Hive': 'hive',
    'Hopin': 'hopin',
    'Hubspot': 'hubspot',
    'Humana': 'humana',
    'Hyperscience': 'hyperscience',
    'Icertis': 'icertis',
    'Imply': 'imply',
    'Indigo Agriculture': 'indigo',
    'Inflection': 'inflection',
    'Innovaccer': 'innovaccer',
    'Instacart': 'instacart',
    'Intercom': 'intercom',
    'Ironclad': 'ironclad',
    'Iterable': 'iterable',
    'Jasper': 'jasper',
    'Jerry': 'jerry',
    'JumpCloud': 'jumpcloud',
    'Juni Learning': 'juni',
    'Juniper Networks': 'junipernetworks',
    'Justworks': 'justworks',
    'Karat': 'karat',
    'Keeper': 'keeper',
    'Kepler': 'kepler',
    'Kindred': 'kindred',
    'Kin Insurance': 'kin',
    'Kira Systems': 'kirasystems',
    'Klarna': 'klarna',
    'Klaviyo': 'klaviyo',
    'Knock': 'knock',
    'Komodo Health': 'komodohealth',
    'Kong': 'kong',
    'Kustomer': 'kustomer',
    'Lacework': 'lacework',
    'Lambda': 'lambda',
    'Latch': 'latch',
    'Lattice': 'lattice',
    'LaunchDarkly': 'launchdarkly',
    'Lemonade': 'lemonade',
    'Lever': 'lever',
    'Linear': 'linear',
    'Linktree': 'linktree',
    'Lithic': 'lithic',
    'Lob': 'lob',
    'LogDNA': 'logdna',
    'LogRocket': 'logrocket',
    'Loom': 'loom',
    'Lucid': 'lucid',
    'Lunchclub': 'lunchclub',
    'Lyft': 'lyft',
    'Lyra Health': 'lyrahealth',
    'Mailchimp': 'mailchimp',
    'Mambu': 'mambu',
    'Mapbox': 'mapbox',
    'Marqeta': 'marqeta',
    'Masterclass': 'masterclass',
    'Materialize': 'materialize',
    'Medallia': 'medallia',
    'Melio': 'melio',
    'Mercury': 'mercury',
    'Metabase': 'metabase',
    'Metaplane': 'metaplane',
    'Metronome': 'metronome',
    'Miro': 'miro',
    'Mixpanel': 'mixpanel',
    'Modal': 'modal',
    'Modern Health': 'modernhealth',
    'Modern Treasury': 'moderntreasury',
    'Modo': 'modo',
    'Monday.com': 'mondaycom',
    'MongoDB': 'mongodb',
    'Monte Carlo': 'montecarlodata',
    'Mosaic': 'mosaic',
    'Mux': 'mux',
    'Narvar': 'narvar',
    'Netlify': 'netlify',
    'Newfront': 'newfront',
    'NewStore': 'newstore',
    'Next Insurance': 'nextinsurance',
    'Nextdoor': 'nextdoor',
    'Niantic': 'niantic',
    'NinjaTrader': 'ninjatrader',
    'Notion': 'notion',
    'Nova Credit': 'novacredit',
    'Nylas': 'nylas',
    'Observable': 'observablehq',
    'Olo': 'olo',
    'Onfido': 'onfido',
    'OneSignal': 'onesignal',
    'OneTrust': 'onetrust',
    'Opendoor': 'opendoor',
    'OpenSea': 'opensea',
    'Ops': 'ops',
    'Orbit': 'orbit',
    'Orchard': 'orchard',
    'Orca Security': 'orcasecurity',
    'Origin': 'origin',
    'Oscar Health': 'oscarhealth',
    'Outreach': 'outreach',
    'OwnBackup': 'ownbackup',
    'Oyster': 'oyster',
    'PagerDuty': 'pagerduty',
    'Palo Alto Networks': 'paloaltonetworks',
    'PandaDoc': 'pandadoc',
    'Panther Labs': 'pantherlabs',
    'Patreon': 'patreon',
    'Payoneer': 'payoneer',
    'Pendo': 'pendo',
    'Persona': 'persona',
    'Pilot': 'pilot',
    'Pinterest': 'pinterest',
    'Pipe': 'pipe',
    'Pitch': 'pitch',
    'PlanetScale': 'planetscale',
    'Plaid': 'plaid',
    'Planetary': 'planetary',
    'Plivo': 'plivo',
    'Pluralsight': 'pluralsight',
    'Podium': 'podium',
    'Polygon': 'polygon',
    'PopSQL': 'popsql',
    'Postman': 'postman',
    'Postscript': 'postscript',
    'Prefect': 'prefect',
    'PrimeRevenue': 'primerevenue',
    'Productboard': 'productboard',
    'Project44': 'project44',
    'Proofpoint': 'proofpoint',
    'Pulley': 'pulley',
    'Pulumi': 'pulumi',
    'Puppet': 'puppet',
    'Qualtrics': 'qualtrics',
    'Quantum Metric': 'quantummetric',
    'Quora': 'quora',
    'Raft': 'raft',
    'Ramp': 'ramp',
    'Raven': 'raven',
    'ReadMe': 'readme',
    'Recurly': 'recurly',
    'Redis': 'redis',
    'Reforge': 'reforge',
    'Relay': 'relay',
    'Remote': 'remote',
    'Render': 'render',
    'Replicate': 'replicate',
    'Retool': 'retool',
    'Ribbon Health': 'ribbonhealth',
    'Rime': 'rime',
    'Ripple': 'ripple',
    'Rippling': 'rippling',
    'Rise8': 'rise8',
    'Ro': 'ro',
    'Robinhood': 'robinhood',
    'Rocket Money': 'rocketmoney',
    'Rootly': 'rootly',
    'Route': 'route',
    'Rudderstack': 'rudderstack',
    'Runway': 'runway',
    'SailPoint': 'sailpoint',
    'Salesloft': 'salesloft',
    'Samsara': 'samsara',
    'Sanity': 'sanity',
    'Scale AI': 'scaleai',
    'Scribd': 'scribd',
    'Secureframe': 'secureframe',
    'Segment': 'segment',
    'Seismic': 'seismic',
    'Sendbird': 'sendbird',
    'Sendoso': 'sendoso',
    'SentinelOne': 'sentinelone',
    'Sentry': 'sentry',
    'ServiceTitan': 'servicetitan',
    'ShipBob': 'shipbob',
    'Shippo': 'shippo',
    'Shopify': 'shopify',
    'Shortcut': 'shortcut',
    'Sigma Computing': 'sigmacomputing',
    'Signifyd': 'signifyd',
    'Simpplr': 'simpplr',
    'SingleStore': 'singlestore',
    'Sisense': 'sisense',
    'Skyflow': 'skyflow',
    'Slab': 'slab',
    'Slack': 'slack',
    'Slice': 'slice',
    'SmartAsset': 'smartasset',
    'Smartcar': 'smartcar',
    'Smartsheet': 'smartsheet',
    'Snap': 'snap',
    'Snapdocs': 'snapdocs',
    'Snorkel AI': 'snorkelai',
    'Snowflake': 'snowflake',
    'Snyk': 'snyk',
    'SoFi': 'sofi',
    'Sourcegraph': 'sourcegraph',
    'Spacelift': 'spacelift',
    'SpaceX': 'spacex',
    'Splashtop': 'splashtop',
    'Splunk': 'splunk',
    'Spotify': 'spotify',
    'Spring Health': 'springhealth',
    'Sprinklr': 'sprinklr',
    'Square': 'square',
    'Squarespace': 'squarespace',
    'Starburst': 'starburst',
    'Stash': 'stash',
    'Statsig': 'statsig',
    'Step': 'step',
    'Stitch Fix': 'stitchfix',
    'Stord': 'stord',
    'Strava': 'strava',
    'StreamNative': 'streamnative',
    'Stripe': 'stripe',
    'Sumo Logic': 'sumologic',
    'Supabase': 'supabase',
    'Suplari': 'suplari',
    'Sword Health': 'swordhealth',
    'Synthesia': 'synthesia',
    'Tailscale': 'tailscale',
    'Tanium': 'tanium',
    'Taskrabbit': 'taskrabbit',
    'Tealium': 'tealium',
    'Tecton': 'tecton',
    'Teleport': 'teleport',
    'Temporal': 'temporal',
    'Terminal': 'terminal',
    'Tessera': 'tessera',
    'The Athletic': 'theathletic',
    'ThoughtSpot': 'thoughtspot',
    'Thrive Market': 'thrivemarket',
    'Thumbtack': 'thumbtack',
    'Timescale': 'timescale',
    'Tines': 'tines',
    'Toast': 'toast',
    'Together AI': 'togetherai',
    'Tonal': 'tonal',
    'Toptal': 'toptal',
    'Torq': 'torq',
    'Traceable': 'traceable',
    'Tray.io': 'tray',
    'Tremendous': 'tremendous',
    'Tribe': 'tribe',
    'Triplebyte': 'triplebyte',
    'Truebill': 'truebill',
    'Truework': 'truework',
    'TuSimple': 'tusimple',
    'Twilio': 'twilio',
    'Twitch': 'twitch',
    'Typeform': 'typeform',
    'Uber': 'uber',
    'Udacity': 'udacity',
    'Udemy': 'udemy',
    'Unqork': 'unqork',
    'Upstart': 'upstart',
    'UserTesting': 'usertesting',
    'Vanta': 'vanta',
    'Varo': 'varo',
    'Vectra': 'vectra',
    'Velocity Global': 'velocityglobal',
    'Vendr': 'vendr',
    'Verkada': 'verkada',
    'Verve': 'verve',
    'Via': 'ridewithvia',
    'Vidyard': 'vidyard',
    'Vimeo': 'vimeo',
    'Vouch': 'vouch',
    'Waabi': 'waabi',
    'Wandb': 'wandb',
    'Wealthfront': 'wealthfront',
    'Wealthsimple': 'wealthsimple',
    'Webflow': 'webflow',
    'Weights & Biases': 'wandb',
    'Whatnot': 'whatnot',
    'Whoop': 'whoop',
    'Wildlife Studios': 'wildlifestudios',
    'Wish': 'wish',
    'Wistia': 'wistia',
    'Wiz': 'wiz',
    'Workato': 'workato',
    'Workiva': 'workiva',
    'Workrise': 'workrise',
    'Writer': 'writer',
    'Xero': 'xero',
    'Zapier': 'zapier',
    'Zendesk': 'zendesk',
    'ZenBusiness': 'zenbusiness',
    'Zenoti': 'zenoti',
    'Zip': 'zip',
    'Zipmoney': 'zipmoney',
    'Zoom': 'zoom',
    'Zoox': 'zoox',
    'Zscaler': 'zscaler',
    'Zuora': 'zuora',
}

# Ashby is used by many modern startups
ASHBY_COMPANIES = {
    'Ashby': 'ashby',
    'Figma': 'figma',
    'Notion': 'notion',
    'Ramp': 'ramp',
    'Vercel': 'vercel',
    'Linear': 'linear',
    'Mercury': 'mercury',
    'Loom': 'loom',
    'Retool': 'retool',
    'Webflow': 'webflow',
    'Scale AI': 'scale',
    'Anduril': 'anduril',
    'Anthropic': 'anthropic',
    'OpenAI': 'openai',
    'Stripe': 'stripe',
    'Airbnb': 'airbnb',
    'Coinbase': 'coinbase',
    'Plaid': 'plaid',
    'Brex': 'brex',
    'Rippling': 'rippling',
    'Deel': 'deel',
    'Remote': 'remote',
    'Gusto': 'gusto',
    'Lattice': 'lattice',
    'Carta': 'carta',
    'Airtable': 'airtable',
    'Miro': 'miro',
    'Coda': 'coda',
    'ClickUp': 'clickup',
    'Asana': 'asana',
    'Monday': 'monday',
    'Supabase': 'supabase',
    'PlanetScale': 'planetscale',
    'Neon': 'neon',
    'Railway': 'railway',
    'Render': 'render',
    'Fly.io': 'fly',
    'Netlify': 'netlify',
    'Cloudflare': 'cloudflare',
    'Fastly': 'fastly',
    'DigitalOcean': 'digitalocean',
    'Vultr': 'vultr',
    'Linode': 'linode',
    'Grafana': 'grafana',
    'Datadog': 'datadog',
    'New Relic': 'newrelic',
    'Sentry': 'sentry',
    'PagerDuty': 'pagerduty',
    'LaunchDarkly': 'launchdarkly',
    'Split': 'split',
    'Optimizely': 'optimizely',
    'Amplitude': 'amplitude',
    'Mixpanel': 'mixpanel',
    'Segment': 'segment',
    'Rudderstack': 'rudderstack',
    'Census': 'census',
    'Hightouch': 'hightouch',
    'Fivetran': 'fivetran',
    'Airbyte': 'airbyte',
    'dbt Labs': 'dbt',
    'Databricks': 'databricks',
    'Snowflake': 'snowflake',
    'BigQuery': 'bigquery',
    'Redshift': 'redshift',
    'Timescale': 'timescale',
    'ClickHouse': 'clickhouse',
    'SingleStore': 'singlestore',
    'CockroachDB': 'cockroachdb',
    'MongoDB': 'mongodb',
    'Redis': 'redis',
    'Elasticsearch': 'elasticsearch',
    'Algolia': 'algolia',
    'Meilisearch': 'meilisearch',
    'Typesense': 'typesense',
    'Pinecone': 'pinecone',
    'Weaviate': 'weaviate',
    'Qdrant': 'qdrant',
    'Chroma': 'chroma',
    'Zilliz': 'zilliz',
    'LangChain': 'langchain',
    'LlamaIndex': 'llamaindex',
    'Weights & Biases': 'wandb',
    'MLflow': 'mlflow',
    'Comet': 'comet',
    'Neptune': 'neptune',
    'Modal': 'modal',
    'Banana': 'banana',
    'Replicate': 'replicate',
    'Hugging Face': 'huggingface',
    'Together AI': 'together',
    'Anyscale': 'anyscale',
    'Ray': 'ray',
    'Prefect': 'prefect',
    'Dagster': 'dagster',
    'Airflow': 'airflow',
    'Temporal': 'temporal',
    'Inngest': 'inngest',
    'Trigger.dev': 'triggerdev',
    'Resend': 'resend',
    'Postmark': 'postmark',
    'SendGrid': 'sendgrid',
    'Mailgun': 'mailgun',
    'Twilio': 'twilio',
    'Vonage': 'vonage',
    'MessageBird': 'messagebird',
    'Sinch': 'sinch',
    'Agora': 'agora',
    'Daily': 'daily',
    'Livekit': 'livekit',
    '100ms': '100ms',
    'Stream': 'stream',
    'Sendbird': 'sendbird',
    'Ably': 'ably',
    'Pusher': 'pusher',
    'PubNub': 'pubnub',
    'Socket.io': 'socketio',
    'Upstash': 'upstash',
    'Nhost': 'nhost',
    'Hasura': 'hasura',
    'Fauna': 'fauna',
    'Xata': 'xata',
    'EdgeDB': 'edgedb',
    'Turso': 'turso',
    'Prisma': 'prisma',
    'Drizzle': 'drizzle',
    'Kysely': 'kysely',
    'tRPC': 'trpc',
    'GraphQL': 'graphql',
    'Apollo': 'apollo',
    'Relay': 'relay',
    'Urql': 'urql',
}

SMARTRECRUITERS_COMPANIES = {
    'Visa': 'visa',
    'IKEA': 'ikea',
    'Bosch': 'bosch',
    'Siemens': 'siemens',
    'Adidas': 'adidas',
    'Puma': 'puma',
    'Continental': 'continental',
    'BMW': 'bmw',
    'Mercedes': 'mercedes',
    'Volkswagen': 'volkswagen',
    'SAP': 'sap',
    'Allianz': 'allianz',
    'Deutsche Bank': 'deutschebank',
    'Commerzbank': 'commerzbank',
    'Munich Re': 'munichre',
    'Bayer': 'bayer',
    'BASF': 'basf',
    'Henkel': 'henkel',
    'Merck': 'merck',
    'Infineon': 'infineon',
    'Zalando': 'zalando',
    'Delivery Hero': 'deliveryhero',
    'HelloFresh': 'hellofresh',
    'N26': 'n26',
    'Personio': 'personio',
    'Celonis': 'celonis',
    'UiPath': 'uipath',
    'Automation Anywhere': 'automationanywhere',
    'Blue Prism': 'blueprism',
    'Dynatrace': 'dynatrace',
    'DataRobot': 'datarobot',
    'C3.ai': 'c3ai',
    'Palantir': 'palantir',
    'Splunk': 'splunk',
    'ServiceNow': 'servicenow',
    'Workday': 'workday',
    'Salesforce': 'salesforce',
    'Adobe': 'adobe',
    'Autodesk': 'autodesk',
    'Intuit': 'intuit',
    'Paypal': 'paypal',
    'Square': 'square',
    'Shopify': 'shopify',
    'Wix': 'wix',
    'HubSpot': 'hubspot',
    'Zendesk': 'zendesk',
    'Freshworks': 'freshworks',
    'Zoho': 'zoho',
    'Monday.com': 'monday',
    'Asana': 'asana',
    'Smartsheet': 'smartsheet',
    'Box': 'box',
    'Dropbox': 'dropbox',
    'DocuSign': 'docusign',
    'Okta': 'okta',
    'CrowdStrike': 'crowdstrike',
    'Zscaler': 'zscaler',
    'Fortinet': 'fortinet',
    'Palo Alto Networks': 'paloalto',
    'Check Point': 'checkpoint',
    'F5': 'f5',
    'Akamai': 'akamai',
    'Cloudflare': 'cloudflare',
    'Fastly': 'fastly',
    'Twilio': 'twilio',
    'RingCentral': 'ringcentral',
    'Zoom': 'zoom',
    'Slack': 'slack',
    'Microsoft': 'microsoft',
    'Google': 'google',
    'Amazon': 'amazon',
    'Meta': 'meta',
    'Apple': 'apple',
    'Netflix': 'netflix',
    'Spotify': 'spotify',
    'Uber': 'uber',
    'Lyft': 'lyft',
    'Airbnb': 'airbnb',
    'DoorDash': 'doordash',
    'Instacart': 'instacart',
    'Grubhub': 'grubhub',
    'Postmates': 'postmates',
    'Gopuff': 'gopuff',
    'Getir': 'getir',
    'Gorillas': 'gorillas',
    'Flink': 'flink',
    'Jokr': 'jokr',
    'Zapp': 'zapp',
}

BAMBOOHR_COMPANIES = {
    'BambooHR': 'bamboohr',
    'Pluralsight': 'pluralsight',
    'Weave': 'weave',
    'Podium': 'podium',
    'Lucid': 'lucid',
    'Domo': 'domo',
    'Qualtrics': 'qualtrics',
    'Divvy': 'divvy',
    'Vivint': 'vivint',
    'Health Catalyst': 'healthcatalyst',
    'Instructure': 'instructure',
    'InsideSales': 'insidesales',
    'Entrata': 'entrata',
    'SimpleNexus': 'simplenexus',
    'Pattern': 'pattern',
    'Recursion': 'recursionpharmaceuticals',
    'MX': 'mx',
    'Impartner': 'impartner',
    'Lendio': 'lendio',
    'Nav': 'nav',
    'Listen360': 'listen360',
    'MarketDial': 'marketdial',
}


class CompanyDiscovery:
    """Discovers companies and their ATS systems"""

    def __init__(self):
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        })
        self.discovered: Dict[str, Dict] = self._load_discovered()

    def _load_discovered(self) -> Dict:
        """Load previously discovered companies"""
        os.makedirs(DATA_DIR, exist_ok=True)
        if os.path.exists(DISCOVERED_COMPANIES_FILE):
            try:
                with open(DISCOVERED_COMPANIES_FILE, 'r') as f:
                    return json.load(f)
            except:
                pass
        return {
            'greenhouse': {},
            'lever': {},
            'ashby': {},
            'smartrecruiters': {},
            'bamboohr': {},
            'last_updated': None
        }

    def _save_discovered(self):
        """Save discovered companies to file"""
        self.discovered['last_updated'] = datetime.now().isoformat()
        os.makedirs(DATA_DIR, exist_ok=True)
        with open(DISCOVERED_COMPANIES_FILE, 'w') as f:
            json.dump(self.discovered, f, indent=2)

    def _check_greenhouse(self, board_id: str) -> bool:
        """Check if a Greenhouse board exists"""
        try:
            url = f"https://boards-api.greenhouse.io/v1/boards/{board_id}/jobs"
            response = self.session.get(url, timeout=10)
            return response.status_code == 200
        except:
            return False

    def _check_lever(self, board_id: str) -> bool:
        """Check if a Lever board exists"""
        try:
            url = f"https://api.lever.co/v0/postings/{board_id}"
            response = self.session.get(url, timeout=10)
            return response.status_code == 200
        except:
            return False

    def _check_ashby(self, board_id: str) -> bool:
        """Check if an Ashby board exists"""
        try:
            url = f"https://api.ashbyhq.com/posting-api/job-board/{board_id}"
            response = self.session.get(url, timeout=10)
            return response.status_code == 200
        except:
            return False

    def _check_smartrecruiters(self, company_id: str) -> bool:
        """Check if a SmartRecruiters company exists"""
        try:
            url = f"https://api.smartrecruiters.com/v1/companies/{company_id}/postings"
            response = self.session.get(url, timeout=10)
            return response.status_code == 200
        except:
            return False

    def _check_bamboohr(self, subdomain: str) -> bool:
        """Check if a BambooHR subdomain exists"""
        try:
            url = f"https://{subdomain}.bamboohr.com/jobs/"
            response = self.session.get(url, timeout=10)
            return response.status_code == 200 and 'job' in response.text.lower()
        except:
            return False

    def discover_from_lists(self, parallel: bool = True) -> Dict[str, int]:
        """Discover companies from curated lists"""
        stats = {
            'greenhouse': 0,
            'lever': 0,
            'ashby': 0,
            'smartrecruiters': 0,
            'bamboohr': 0,
        }

        # Add all curated companies
        all_checks = []

        # Greenhouse companies
        for name, board_id in GREENHOUSE_COMPANIES_EXTENDED.items():
            all_checks.append(('greenhouse', name, board_id, self._check_greenhouse))

        # Lever companies
        for name, board_id in LEVER_COMPANIES_EXTENDED.items():
            all_checks.append(('lever', name, board_id, self._check_lever))

        # Ashby companies
        for name, board_id in ASHBY_COMPANIES.items():
            all_checks.append(('ashby', name, board_id, self._check_ashby))

        # SmartRecruiters companies
        for name, company_id in SMARTRECRUITERS_COMPANIES.items():
            all_checks.append(('smartrecruiters', name, company_id, self._check_smartrecruiters))

        # BambooHR companies
        for name, subdomain in BAMBOOHR_COMPANIES.items():
            all_checks.append(('bamboohr', name, subdomain, self._check_bamboohr))

        logger.info(f"Checking {len(all_checks)} companies across all ATS systems...")

        def check_company(item):
            ats, name, board_id, check_func = item
            try:
                if check_func(board_id):
                    return (ats, name, board_id)
            except:
                pass
            return None

        if parallel:
            with ThreadPoolExecutor(max_workers=20) as executor:
                futures = {executor.submit(check_company, item): item for item in all_checks}
                for future in as_completed(futures):
                    result = future.result()
                    if result:
                        ats, name, board_id = result
                        if name not in self.discovered[ats]:
                            self.discovered[ats][name] = board_id
                            stats[ats] += 1
                            logger.info(f"Discovered {ats}: {name}")
        else:
            for item in all_checks:
                result = check_company(item)
                if result:
                    ats, name, board_id = result
                    if name not in self.discovered[ats]:
                        self.discovered[ats][name] = board_id
                        stats[ats] += 1
                        logger.info(f"Discovered {ats}: {name}")
                time.sleep(0.1)

        self._save_discovered()
        return stats

    def get_all_companies(self) -> Dict[str, Dict[str, str]]:
        """Get all discovered companies"""
        return self.discovered

    def get_stats(self) -> Dict:
        """Get discovery statistics"""
        return {
            'greenhouse': len(self.discovered.get('greenhouse', {})),
            'lever': len(self.discovered.get('lever', {})),
            'ashby': len(self.discovered.get('ashby', {})),
            'smartrecruiters': len(self.discovered.get('smartrecruiters', {})),
            'bamboohr': len(self.discovered.get('bamboohr', {})),
            'total': sum(len(self.discovered.get(k, {})) for k in ['greenhouse', 'lever', 'ashby', 'smartrecruiters', 'bamboohr']),
            'last_updated': self.discovered.get('last_updated'),
        }


def main():
    """Run company discovery"""
    import argparse

    parser = argparse.ArgumentParser(description='Discover companies and their ATS systems')
    parser.add_argument('--parallel', '-p', action='store_true', help='Use parallel processing')
    args = parser.parse_args()

    discovery = CompanyDiscovery()

    logger.info("Starting company discovery...")
    stats = discovery.discover_from_lists(parallel=args.parallel)

    print("\n" + "=" * 60)
    print("DISCOVERY COMPLETE")
    print("=" * 60)
    print(f"New Greenhouse companies: {stats['greenhouse']}")
    print(f"New Lever companies: {stats['lever']}")
    print(f"New Ashby companies: {stats['ashby']}")
    print(f"New SmartRecruiters companies: {stats['smartrecruiters']}")
    print(f"New BambooHR companies: {stats['bamboohr']}")
    print(f"\nTotal companies in database: {discovery.get_stats()['total']}")
    print("=" * 60)

    return discovery.get_stats()


if __name__ == "__main__":
    main()
